version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zoo
    restart: always
    ports:
      - "2181:2181"
    environment:
      # ZOO_MY_ID: 0
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - app-tier

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "8093:8093"
      - "29092:29092"
    networks:
      - app-tier
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://192.168.1.100:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  manager:
    image: kafkamanager/kafka-manager
    container_name: kafka-manager
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge